import type { Locale } from './config';

type HubCopy = {
  personas: {
    label: string;
    title: string;
    description: string;
    learnMore: string;
    missingTitle: string;
    missingDescription: string;
    start: string;
    ctaTitle: string;
    ctaDescription: string;
    ctaButton: string;
  };
  stateTaxes: {
    label: string;
    title: string;
    description: string;
    overviewTitle: string;
    overviewOne: string;
    overviewTwo: string;
    risk: Record<'extreme' | 'high' | 'moderate' | 'low', string>;
    readGuide: string;
    missingTitle: string;
    missingDescription: string;
    start: string;
    ctaTitle: string;
    ctaDescription: string;
    ctaButton: string;
  };
  forms: {
    label: string;
    title: string;
    description: string;
    readGuide: string;
    missingTitle: string;
    missingDescription: string;
    start: string;
    ctaTitle: string;
    ctaDescription: string;
    ctaButton: string;
  };
  intake: {
    eyebrow: string;
    title: string;
    description: string;
    step: string;
    of: string;
    back: string;
    next: string;
    submit: string;
    submitting: string;
    privacy: string;
  };
};

const en: HubCopy = {
  personas: {
    label: 'Who We Help', title: 'Tax Filing for Every Kind of American Abroad',
    description: 'Your tax situation depends on how you earn, where you live, and what you own. Choose the path that matches your life and see how FileAbroad can help.',
    learnMore: 'Learn more', missingTitle: "Don't see your situation?",
    missingDescription: 'Every expat situation is unique. Start the free intake and tell us about your country, income, and filing history. Chip will recommend the right scope and next steps.',
    start: 'Start the free intake', ctaTitle: 'Ready to File?', ctaDescription: 'No matter your situation, the first step is the same: a 3-minute intake form.', ctaButton: 'Start Your Filing',
  },
  stateTaxes: {
    label: 'State Tax Guides', title: 'State Tax Obligations for Americans Abroad',
    description: 'Some states never let go. Learn which states chase expats for tax, how to terminate domicile, and what traps to avoid.',
    overviewTitle: 'The State Tax Trap',
    overviewOne: 'Federal tax obligations follow US citizens everywhere. But state tax obligations depend on domicile and residency rules that vary dramatically by state. Some states aggressively audit former residents; others have no income tax at all.',
    overviewTwo: 'Even if you eliminate federal tax liability through the FEIE or FTC, you may still owe state tax if your former state considers you a resident. Terminating state residency properly is an important pre-departure step.',
    risk: { extreme: 'Extreme Persistence', high: 'High Persistence', moderate: 'Moderate Persistence', low: 'Low Persistence' },
    readGuide: 'Read guide', missingTitle: 'Not sure if your former state still taxes you?',
    missingDescription: 'State residency rules are complex and fact-specific. FileAbroad reviews your domicile history, state ties, and income sources to recommend whether—and how—to terminate state tax obligations.',
    start: 'Start the free intake', ctaTitle: 'State Tax Questions?', ctaDescription: "The right answer depends on your state, your ties, and your income. Let's review your facts.", ctaButton: 'Get a Filing Recommendation',
  },
  forms: {
    label: 'Tax Form Library', title: 'IRS Forms for Americans Abroad',
    description: 'Plain-English explainers for the forms that matter most to expats. Each guide covers who must file, what to report, common mistakes, and how FileAbroad can help.',
    readGuide: 'Read guide', missingTitle: 'Not sure which forms you need?',
    missingDescription: 'The right forms depend on your country, income type, foreign accounts, and asset profile. FileAbroad reviews your facts and recommends the exact forms required in a written scope before any work begins.',
    start: 'Start the free intake', ctaTitle: 'Forms Are Just the Beginning', ctaDescription: 'Understanding the forms is step one. Filing them correctly is what protects you.', ctaButton: 'View All Services',
  },
  intake: {
    eyebrow: 'GET STARTED', title: 'FileAbroad Tax Intake',
    description: 'Thanks for reaching out about your U.S. tax filing. This quick form takes about 3 minutes and helps me prepare for our intake review. The more accurately you answer, the better I can recommend the next step.',
    step: 'Step', of: 'of', back: 'Back', next: 'Next', submit: 'Submit', submitting: 'Submitting...',
    privacy: 'This form is for preliminary facts only. FileAbroad uses named service providers described in the privacy policy; sensitive tax documents belong in the secure Encyro portal.',
  },
};

export const localizedPageCopy: Record<Locale, HubCopy> = {
  en,
  es: {
    personas: { label: 'A quién ayudamos', title: 'Declaración de impuestos para cada tipo de estadounidense en el extranjero', description: 'Su situación fiscal depende de cómo gana dinero, dónde vive y qué posee. Elija el camino que corresponde a su vida y vea cómo puede ayudar FileAbroad.', learnMore: 'Ver más', missingTitle: '¿No ve su situación?', missingDescription: 'Cada situación de expatriado es única. Inicie la admisión gratuita y cuéntenos su país, ingresos e historial de presentación. Chip recomendará el alcance y los próximos pasos.', start: 'Iniciar la admisión gratuita', ctaTitle: '¿Listo para presentar?', ctaDescription: 'Sin importar su situación, el primer paso es el mismo: un formulario de admisión de 3 minutos.', ctaButton: 'Iniciar mi declaración' },
    stateTaxes: { label: 'Guías de impuestos estatales', title: 'Obligaciones de impuestos estatales para estadounidenses en el extranjero', description: 'Algunos estados nunca lo dejan ir. Descubra qué estados persiguen a los expatriados, cómo terminar el domicilio y qué errores evitar.', overviewTitle: 'La trampa de los impuestos estatales', overviewOne: 'Las obligaciones fiscales federales siguen a los ciudadanos estadounidenses a cualquier lugar. Las obligaciones estatales dependen del domicilio y de reglas de residencia que cambian mucho entre estados.', overviewTwo: 'Aunque elimine la obligación fiscal federal mediante FEIE o FTC, todavía puede deber impuestos estatales si su antiguo estado lo considera residente. Terminar correctamente la residencia estatal es un paso importante antes de mudarse al extranjero.', risk: { extreme: 'Persistencia extrema', high: 'Persistencia alta', moderate: 'Persistencia moderada', low: 'Persistencia baja' }, readGuide: 'Leer la guía', missingTitle: '¿No sabe si su antiguo estado todavía le cobra impuestos?', missingDescription: 'Las reglas de residencia estatal dependen de los hechos. FileAbroad revisa su historial de domicilio, vínculos estatales y fuentes de ingresos para recomendar el siguiente paso.', start: 'Iniciar la admisión gratuita', ctaTitle: '¿Preguntas sobre impuestos estatales?', ctaDescription: 'La respuesta depende de su estado, sus vínculos y sus ingresos. Revisemos sus hechos.', ctaButton: 'Obtener una recomendación' },
    forms: { label: 'Biblioteca de formularios fiscales', title: 'Formularios del IRS para estadounidenses en el extranjero', description: 'Guías en español para los formularios que más importan a los expatriados. Cada guía explica quién debe presentar, qué declarar, errores comunes y cómo puede ayudar FileAbroad.', readGuide: 'Leer la guía', missingTitle: '¿No sabe qué formularios necesita?', missingDescription: 'Los formularios correctos dependen de su país, ingresos, cuentas extranjeras y activos. FileAbroad revisa sus hechos y recomienda un alcance escrito antes de comenzar.', start: 'Iniciar la admisión gratuita', ctaTitle: 'Los formularios son solo el comienzo', ctaDescription: 'Entender los formularios es el primer paso. Presentarlos correctamente es lo que le protege.', ctaButton: 'Ver todos los servicios' },
    intake: { eyebrow: 'COMIENCE AQUÍ', title: 'Admisión fiscal de FileAbroad', description: 'Gracias por comunicarse sobre su declaración de impuestos de EE. UU. Este formulario tarda unos 3 minutos y ayuda a preparar la revisión inicial. Cuanto más precisas sean sus respuestas, mejor podremos recomendar el siguiente paso.', step: 'Paso', of: 'de', back: 'Atrás', next: 'Siguiente', submit: 'Enviar', submitting: 'Enviando...', privacy: 'Este formulario solo recopila datos preliminares. FileAbroad usa los proveedores indicados en la política de privacidad; los documentos fiscales sensibles deben enviarse por el portal seguro de Encyro.' },
  },
  pt: {
    personas: { label: 'Quem ajudamos', title: 'Declaração de impostos para cada tipo de americano no exterior', description: 'A sua situação fiscal depende de como ganha dinheiro, onde vive e o que possui. Escolha o caminho que corresponde à sua vida e veja como a FileAbroad pode ajudar.', learnMore: 'Saiba mais', missingTitle: 'Não encontra a sua situação?', missingDescription: 'Cada situação de expatriado é única. Comece a admissão gratuita e conte-nos o seu país, rendimentos e histórico de declarações. O Chip recomendará o âmbito e os próximos passos.', start: 'Iniciar a admissão gratuita', ctaTitle: 'Pronto para declarar?', ctaDescription: 'Qualquer que seja a sua situação, o primeiro passo é o mesmo: um formulário de admissão de 3 minutos.', ctaButton: 'Iniciar a declaração' },
    stateTaxes: { label: 'Guias de impostos estaduais', title: 'Obrigações de impostos estaduais para americanos no exterior', description: 'Alguns estados nunca o deixam partir. Saiba quais estados cobram impostos de expatriados, como terminar o domicílio e que armadilhas evitar.', overviewTitle: 'A armadilha dos impostos estaduais', overviewOne: 'As obrigações fiscais federais acompanham os cidadãos americanos em qualquer lugar. As obrigações estaduais dependem do domicílio e de regras de residência que variam muito entre estados.', overviewTwo: 'Mesmo que elimine o imposto federal através do FEIE ou FTC, ainda pode dever imposto estadual se o antigo estado o considerar residente. Terminar corretamente a residência estadual é um passo importante antes de mudar para o exterior.', risk: { extreme: 'Persistência extrema', high: 'Persistência alta', moderate: 'Persistência moderada', low: 'Persistência baixa' }, readGuide: 'Ler o guia', missingTitle: 'Não sabe se o antigo estado ainda o tributa?', missingDescription: 'As regras de residência estadual dependem dos seus factos. A FileAbroad analisa o histórico de domicílio, os vínculos estaduais e as fontes de rendimento para recomendar o próximo passo.', start: 'Iniciar a admissão gratuita', ctaTitle: 'Dúvidas sobre impostos estaduais?', ctaDescription: 'A resposta depende do estado, dos vínculos e dos rendimentos. Vamos analisar os seus factos.', ctaButton: 'Obter uma recomendação' },
    forms: { label: 'Biblioteca de formulários fiscais', title: 'Formulários do IRS para americanos no exterior', description: 'Guias em português para os formulários mais importantes para expatriados. Cada guia explica quem deve apresentar, o que declarar, erros comuns e como a FileAbroad pode ajudar.', readGuide: 'Ler o guia', missingTitle: 'Não sabe quais formulários precisa?', missingDescription: 'Os formulários corretos dependem do país, rendimento, contas estrangeiras e ativos. A FileAbroad analisa os seus factos e recomenda um âmbito escrito antes de começar.', start: 'Iniciar a admissão gratuita', ctaTitle: 'Os formulários são apenas o começo', ctaDescription: 'Compreender os formulários é o primeiro passo. Apresentá-los corretamente é o que o protege.', ctaButton: 'Ver todos os serviços' },
    intake: { eyebrow: 'COMECE AQUI', title: 'Admissão fiscal da FileAbroad', description: 'Obrigado por nos contactar sobre a sua declaração de impostos dos EUA. Este formulário demora cerca de 3 minutos e ajuda a preparar a revisão inicial. Quanto mais precisas forem as respostas, melhor poderemos recomendar o próximo passo.', step: 'Etapa', of: 'de', back: 'Voltar', next: 'Seguinte', submit: 'Enviar', submitting: 'A enviar...', privacy: 'Este formulário recolhe apenas factos preliminares. A FileAbroad usa os fornecedores indicados na política de privacidade; documentos fiscais sensíveis devem ser enviados pelo portal seguro Encyro.' },
  },
  fr: {
    personas: { label: 'Qui aidons-nous ?', title: 'Déclaration fiscale pour chaque type d’Américain à l’étranger', description: 'Votre situation fiscale dépend de vos revenus, de votre lieu de vie et de vos biens. Choisissez le parcours qui correspond à votre vie et découvrez comment FileAbroad peut vous aider.', learnMore: 'En savoir plus', missingTitle: 'Vous ne voyez pas votre situation ?', missingDescription: 'Chaque situation d’expatrié est unique. Commencez l’admission gratuite et indiquez votre pays, vos revenus et votre historique de déclaration. Chip recommandera le périmètre et les prochaines étapes.', start: 'Commencer l’admission gratuite', ctaTitle: 'Prêt à déclarer ?', ctaDescription: 'Quelle que soit votre situation, la première étape est la même : un formulaire d’admission de 3 minutes.', ctaButton: 'Commencer ma déclaration' },
    stateTaxes: { label: 'Guides sur les impôts des États', title: 'Obligations fiscales des États pour les Américains à l’étranger', description: 'Certains États ne vous oublient jamais. Découvrez lesquels imposent encore les expatriés, comment mettre fin au domicile fiscal et quels pièges éviter.', overviewTitle: 'Le piège de l’impôt d’État', overviewOne: 'Les obligations fiscales fédérales suivent les citoyens américains partout. Les obligations des États dépendent du domicile et de règles de résidence qui varient fortement selon l’État.', overviewTwo: 'Même si le FEIE ou le FTC réduit votre impôt fédéral, vous pouvez encore devoir un impôt d’État si votre ancien État vous considère résident. Mettre fin correctement à la résidence est une étape importante avant le départ.', risk: { extreme: 'Persistance extrême', high: 'Forte persistance', moderate: 'Persistance modérée', low: 'Faible persistance' }, readGuide: 'Lire le guide', missingTitle: 'Votre ancien État vous impose-t-il encore ?', missingDescription: 'Les règles de résidence sont propres à chaque situation. FileAbroad examine votre domicile, vos liens avec l’État et vos revenus pour recommander la prochaine étape.', start: 'Commencer l’admission gratuite', ctaTitle: 'Questions sur l’impôt d’État ?', ctaDescription: 'La réponse dépend de votre État, de vos liens et de vos revenus. Examinons vos faits.', ctaButton: 'Obtenir une recommandation' },
    forms: { label: 'Bibliothèque des formulaires fiscaux', title: 'Formulaires IRS pour les Américains à l’étranger', description: 'Des guides en français sur les formulaires les plus importants pour les expatriés. Chaque guide explique qui doit déclarer, quoi indiquer, les erreurs courantes et comment FileAbroad peut aider.', readGuide: 'Lire le guide', missingTitle: 'Vous ne savez pas quels formulaires utiliser ?', missingDescription: 'Les bons formulaires dépendent de votre pays, de vos revenus, de vos comptes étrangers et de vos actifs. FileAbroad examine vos faits et recommande un périmètre écrit avant tout travail.', start: 'Commencer l’admission gratuite', ctaTitle: 'Les formulaires ne sont que le début', ctaDescription: 'Comprendre les formulaires est la première étape. Les remplir correctement vous protège.', ctaButton: 'Voir tous les services' },
    intake: { eyebrow: 'COMMENCER', title: 'Admission fiscale FileAbroad', description: 'Merci de nous contacter au sujet de votre déclaration fiscale américaine. Ce formulaire prend environ 3 minutes et prépare notre examen initial. Des réponses précises permettent de recommander la prochaine étape.', step: 'Étape', of: 'sur', back: 'Retour', next: 'Suivant', submit: 'Envoyer', submitting: 'Envoi...', privacy: 'Ce formulaire recueille uniquement des faits préliminaires. FileAbroad utilise les prestataires décrits dans la politique de confidentialité ; les documents fiscaux sensibles doivent être transmis via le portail sécurisé Encyro.' },
  },
  de: {
    personas: { label: 'Wem wir helfen', title: 'Steuererklärungen für jede Art von Amerikaner im Ausland', description: 'Ihre Steuersituation hängt davon ab, wie Sie verdienen, wo Sie leben und was Sie besitzen. Wählen Sie den passenden Weg und erfahren Sie, wie FileAbroad helfen kann.', learnMore: 'Mehr erfahren', missingTitle: 'Ihre Situation ist nicht dabei?', missingDescription: 'Jede Expat-Situation ist anders. Starten Sie die kostenlose Erfassung und nennen Sie Land, Einkommen und Erklärungshistorie. Chip empfiehlt Umfang und nächste Schritte.', start: 'Kostenlose Erfassung starten', ctaTitle: 'Bereit zur Abgabe?', ctaDescription: 'Unabhängig von Ihrer Situation beginnt alles mit einem Erfassungsformular von etwa 3 Minuten.', ctaButton: 'Erklärung starten' },
    stateTaxes: { label: 'Leitfäden zu Bundesstaatensteuern', title: 'Steuerpflichten der Bundesstaaten für Amerikaner im Ausland', description: 'Manche Bundesstaaten lassen Sie nie los. Erfahren Sie, welche Staaten Expats besteuern, wie Sie den Wohnsitz beenden und welche Fallen drohen.', overviewTitle: 'Die Falle der Bundesstaatensteuer', overviewOne: 'Die Bundessteuerpflicht folgt US-Bürgern überallhin. Die Steuerpflicht eines Bundesstaats hängt jedoch von Wohnsitz und Aufenthaltsregeln ab, die sich stark unterscheiden.', overviewTwo: 'Auch wenn FEIE oder FTC die Bundessteuer senkt, kann weiterhin eine Staatssteuer anfallen, wenn der frühere Staat Sie als ansässig betrachtet. Die Beendigung der staatlichen Ansässigkeit ist vor dem Umzug wichtig.', risk: { extreme: 'Extrem hartnäckig', high: 'Sehr hartnäckig', moderate: 'Mäßig hartnäckig', low: 'Wenig hartnäckig' }, readGuide: 'Leitfaden lesen', missingTitle: 'Besteuert Ihr früherer Staat Sie noch?', missingDescription: 'Die Regeln für die Ansässigkeit hängen von den Tatsachen ab. FileAbroad prüft Wohnsitz, Bindungen und Einkommensquellen und empfiehlt den nächsten Schritt.', start: 'Kostenlose Erfassung starten', ctaTitle: 'Fragen zur Bundesstaatensteuer?', ctaDescription: 'Die Antwort hängt von Staat, Bindungen und Einkommen ab. Prüfen wir Ihre Tatsachen.', ctaButton: 'Empfehlung erhalten' },
    forms: { label: 'Bibliothek der Steuerformulare', title: 'IRS-Formulare für Amerikaner im Ausland', description: 'Deutsche Erläuterungen zu den wichtigsten Formularen für Expats. Jeder Leitfaden erklärt Abgabepflicht, Inhalte, typische Fehler und wie FileAbroad helfen kann.', readGuide: 'Leitfaden lesen', missingTitle: 'Welche Formulare brauchen Sie?', missingDescription: 'Die richtigen Formulare hängen von Land, Einkommen, Auslandskonten und Vermögen ab. FileAbroad prüft Ihre Fakten und empfiehlt vor Beginn einen schriftlichen Umfang.', start: 'Kostenlose Erfassung starten', ctaTitle: 'Formulare sind nur der Anfang', ctaDescription: 'Formulare zu verstehen ist der erste Schritt. Die korrekte Abgabe schützt Sie.', ctaButton: 'Alle Leistungen ansehen' },
    intake: { eyebrow: 'JETZT STARTEN', title: 'FileAbroad Steuer-Erfassung', description: 'Danke für Ihre Anfrage zur US-Steuererklärung. Dieses kurze Formular dauert etwa 3 Minuten und hilft bei der ersten Prüfung. Je genauer Ihre Antworten sind, desto besser können wir den nächsten Schritt empfehlen.', step: 'Schritt', of: 'von', back: 'Zurück', next: 'Weiter', submit: 'Senden', submitting: 'Wird gesendet...', privacy: 'Dieses Formular sammelt nur vorläufige Fakten. FileAbroad nutzt die in der Datenschutzrichtlinie genannten Anbieter; sensible Steuerunterlagen gehören in das sichere Encyro-Portal.' },
  },
  it: {
    personas: { label: 'Chi aiutiamo', title: 'Dichiarazione fiscale per ogni americano che vive all’estero', description: 'La situazione fiscale dipende da come guadagni, dove vivi e cosa possiedi. Scegli il percorso adatto alla tua vita e scopri come FileAbroad può aiutarti.', learnMore: 'Scopri di più', missingTitle: 'Non trovi la tua situazione?', missingDescription: 'Ogni situazione di espatriato è unica. Inizia la raccolta gratuita e indica paese, reddito e storico delle dichiarazioni. Chip consiglierà ambito e prossimi passi.', start: 'Inizia la raccolta gratuita', ctaTitle: 'Pronto a presentare?', ctaDescription: 'Qualunque sia la situazione, il primo passo è lo stesso: un modulo di raccolta di 3 minuti.', ctaButton: 'Inizia la dichiarazione' },
    stateTaxes: { label: 'Guide sulle imposte statali', title: 'Obblighi fiscali statali per gli americani all’estero', description: 'Alcuni Stati non ti lasciano mai andare. Scopri quali Stati tassano ancora gli espatriati, come chiudere il domicilio e quali errori evitare.', overviewTitle: 'La trappola delle imposte statali', overviewOne: 'Gli obblighi fiscali federali seguono i cittadini statunitensi ovunque. Gli obblighi statali dipendono da domicilio e residenza, con regole molto diverse da uno Stato all’altro.', overviewTwo: 'Anche se FEIE o FTC riducono l’imposta federale, potresti dover pagare imposte statali se il precedente Stato ti considera residente. Chiudere correttamente la residenza è un passaggio importante prima della partenza.', risk: { extreme: 'Persistenza estrema', high: 'Persistenza elevata', moderate: 'Persistenza moderata', low: 'Persistenza bassa' }, readGuide: 'Leggi la guida', missingTitle: 'Il tuo precedente Stato ti tassa ancora?', missingDescription: 'Le regole di residenza dipendono dai fatti. FileAbroad esamina domicilio, legami statali e fonti di reddito per indicare il prossimo passo.', start: 'Inizia la raccolta gratuita', ctaTitle: 'Domande sulle imposte statali?', ctaDescription: 'La risposta dipende da Stato, legami e reddito. Esaminiamo i tuoi fatti.', ctaButton: 'Ottieni una raccomandazione' },
    forms: { label: 'Biblioteca dei moduli fiscali', title: 'Moduli IRS per gli americani all’estero', description: 'Guide in italiano sui moduli più importanti per gli espatriati. Ogni guida spiega chi deve presentare, cosa dichiarare, gli errori comuni e come FileAbroad può aiutare.', readGuide: 'Leggi la guida', missingTitle: 'Non sai quali moduli servono?', missingDescription: 'I moduli corretti dipendono da Paese, reddito, conti esteri e attività. FileAbroad esamina i fatti e consiglia un ambito scritto prima di iniziare.', start: 'Inizia la raccolta gratuita', ctaTitle: 'I moduli sono solo l’inizio', ctaDescription: 'Capire i moduli è il primo passo. Presentarli correttamente ti protegge.', ctaButton: 'Vedi tutti i servizi' },
    intake: { eyebrow: 'INIZIA QUI', title: 'Raccolta fiscale FileAbroad', description: 'Grazie per averci contattato sulla tua dichiarazione fiscale statunitense. Questo modulo richiede circa 3 minuti e prepara la revisione iniziale. Risposte precise aiutano a consigliare il prossimo passo.', step: 'Passo', of: 'di', back: 'Indietro', next: 'Avanti', submit: 'Invia', submitting: 'Invio...', privacy: 'Questo modulo raccoglie solo fatti preliminari. FileAbroad usa i fornitori indicati nella privacy policy; i documenti fiscali sensibili devono essere inviati tramite il portale sicuro Encyro.' },
  },
  nl: {
    personas: { label: 'Wie wij helpen', title: 'Belastingaangifte voor iedere Amerikaan in het buitenland', description: 'Uw fiscale situatie hangt af van inkomen, woonplaats en bezit. Kies het pad dat bij uw leven past en ontdek hoe FileAbroad kan helpen.', learnMore: 'Meer informatie', missingTitle: 'Staat uw situatie er niet bij?', missingDescription: 'Elke expatsituatie is uniek. Start de gratis intake en vertel ons over land, inkomen en aangiftehistorie. Chip adviseert over scope en volgende stappen.', start: 'Gratis intake starten', ctaTitle: 'Klaar om aangifte te doen?', ctaDescription: 'Welke situatie u ook heeft, de eerste stap is hetzelfde: een intakeformulier van 3 minuten.', ctaButton: 'Aangifte starten' },
    stateTaxes: { label: 'Gidsen over staatsbelasting', title: 'Staatsbelasting voor Amerikanen in het buitenland', description: 'Sommige staten laten u nooit los. Ontdek welke staten expats blijven belasten, hoe u uw woonplaats beëindigt en welke valkuilen bestaan.', overviewTitle: 'De valkuil van staatsbelasting', overviewOne: 'Federale belastingverplichtingen volgen Amerikaanse burgers overal. Staatsbelasting hangt af van domicilie en woonplaatsregels, die sterk per staat verschillen.', overviewTwo: 'Ook als FEIE of FTC de federale belasting verlaagt, kunt u staatsbelasting verschuldigd blijven als uw vroegere staat u als inwoner ziet. Een juiste beëindiging van de staatsresidentie is een belangrijke stap vóór vertrek.', risk: { extreme: 'Extreem hardnekkig', high: 'Zeer hardnekkig', moderate: 'Gemiddeld hardnekkig', low: 'Weinig hardnekkig' }, readGuide: 'Gids lezen', missingTitle: 'Belast uw vroegere staat u nog?', missingDescription: 'Residentieregels zijn feitelijk en specifiek. FileAbroad bekijkt domicilie, banden met de staat en inkomensbronnen om de volgende stap aan te raden.', start: 'Gratis intake starten', ctaTitle: 'Vragen over staatsbelasting?', ctaDescription: 'Het antwoord hangt af van staat, banden en inkomen. Laten we uw feiten bekijken.', ctaButton: 'Advies ontvangen' },
    forms: { label: 'Bibliotheek met belastingformulieren', title: 'IRS-formulieren voor Amerikanen in het buitenland', description: 'Gidsen in het Nederlands over de belangrijkste formulieren voor expats. Elke gids behandelt aangifteplicht, rapportage, veelgemaakte fouten en hoe FileAbroad kan helpen.', readGuide: 'Gids lezen', missingTitle: 'Weet u niet welke formulieren nodig zijn?', missingDescription: 'De juiste formulieren hangen af van land, inkomen, buitenlandse rekeningen en bezittingen. FileAbroad bekijkt uw feiten en legt de scope schriftelijk vast.', start: 'Gratis intake starten', ctaTitle: 'Formulieren zijn slechts het begin', ctaDescription: 'Formulieren begrijpen is de eerste stap. Ze correct indienen beschermt u.', ctaButton: 'Alle diensten bekijken' },
    intake: { eyebrow: 'BEGIN HIER', title: 'FileAbroad belastingintake', description: 'Bedankt voor uw bericht over uw Amerikaanse belastingaangifte. Dit korte formulier duurt ongeveer 3 minuten en helpt bij de eerste beoordeling. Nauwkeurige antwoorden maken een betere aanbeveling mogelijk.', step: 'Stap', of: 'van', back: 'Terug', next: 'Volgende', submit: 'Versturen', submitting: 'Wordt verstuurd...', privacy: 'Dit formulier verzamelt alleen voorlopige feiten. FileAbroad gebruikt de dienstverleners uit het privacybeleid; gevoelige belastingdocumenten horen in het beveiligde Encyro-portaal.' },
  },
  ja: {
    personas: { label: 'サポート対象', title: '海外に住むアメリカ人のための税務申告', description: '税務状況は、収入の得方、住んでいる場所、保有資産によって変わります。あなたに合う申告の道筋を選び、FileAbroadの支援内容をご確認ください。', learnMore: '詳しく見る', missingTitle: '該当する状況が見つかりませんか？', missingDescription: '海外居住者の状況は一人ひとり異なります。国、収入、申告履歴を無料フォームでお知らせください。Chipが範囲と次の手順を案内します。', start: '無料フォームを開始', ctaTitle: '申告を始めますか？', ctaDescription: '状況にかかわらず、最初の手順は約3分の確認フォームです。', ctaButton: '申告を開始' },
    stateTaxes: { label: '州税ガイド', title: '海外在住アメリカ人の州税義務', description: '州によっては海外へ移住しても税務上のつながりが残ります。州税、住所の終了手続き、注意点を確認しましょう。', overviewTitle: '州税の落とし穴', overviewOne: '連邦税の義務は米国市民にどこまでも付いてきます。一方、州税は住所と居住者規則によって決まり、州ごとに大きく異なります。', overviewTwo: 'FEIEやFTCで連邦税が減っても、以前の州が居住者と判断すれば州税が発生する場合があります。海外移住前に州の居住関係を正しく終了することが重要です。', risk: { extreme: '非常に継続的', high: '継続性が高い', moderate: '継続性が中程度', low: '継続性が低い' }, readGuide: 'ガイドを読む', missingTitle: '以前の州からまだ課税されますか？', missingDescription: '州の居住者規則は事実関係によって変わります。FileAbroadが住所、州とのつながり、収入源を確認し、次の手順を案内します。', start: '無料フォームを開始', ctaTitle: '州税について質問がありますか？', ctaDescription: '答えは州、つながり、収入によって変わります。事実関係を確認しましょう。', ctaButton: '申告の案内を受ける' },
    forms: { label: '税務フォームライブラリ', title: '海外在住アメリカ人のためのIRSフォーム', description: '海外居住者に重要なフォームを日本語で解説します。提出者、申告内容、よくある間違い、FileAbroadの支援範囲を確認できます。', readGuide: 'ガイドを読む', missingTitle: '必要なフォームが分かりませんか？', missingDescription: '必要なフォームは国、収入、海外口座、資産によって異なります。FileAbroadが事実関係を確認し、開始前に範囲を書面で提示します。', start: '無料フォームを開始', ctaTitle: 'フォームは最初の一歩です', ctaDescription: 'フォームを理解することが第一歩です。正確な提出があなたを守ります。', ctaButton: 'サービスを見る' },
    intake: { eyebrow: 'ここから開始', title: 'FileAbroad税務確認フォーム', description: '米国税務申告についてお問い合わせいただきありがとうございます。この短いフォームは約3分で、初回確認の準備に役立ちます。正確な回答ほど適切な次の手順を案内できます。', step: 'ステップ', of: '/', back: '戻る', next: '次へ', submit: '送信', submitting: '送信中...', privacy: 'このフォームは予備的な事実のみを収集します。機密性の高い税務書類は安全なEncyroポータルで送信してください。' },
  },
  zh: {
    personas: { label: '我们帮助谁', title: '为每一种海外美国人提供报税支持', description: '您的税务情况取决于收入来源、居住地和资产。选择符合您生活情况的路径，了解FileAbroad如何提供帮助。', learnMore: '了解更多', missingTitle: '没有找到您的情况？', missingDescription: '每个海外居住者的情况都不同。请通过免费表单告诉我们国家、收入和申报历史，Chip会建议服务范围和下一步。', start: '开始免费表单', ctaTitle: '准备开始申报了吗？', ctaDescription: '无论您的情况如何，第一步都是填写约3分钟的确认表单。', ctaButton: '开始申报' },
    stateTaxes: { label: '州税指南', title: '海外美国人的州税义务', description: '有些州不会轻易结束与您的税务联系。了解哪些州仍会向海外居民征税、如何结束住所关系以及需要避免的风险。', overviewTitle: '州税陷阱', overviewOne: '联邦税务义务会跟随美国公民到任何地方。州税义务则取决于住所和居住规则，而这些规则因州而异。', overviewTwo: '即使FEIE或FTC降低了联邦税，如果原居住州仍将您视为居民，您可能仍需缴纳州税。正确结束州居民关系是移居海外前的重要步骤。', risk: { extreme: '持续性极高', high: '持续性高', moderate: '持续性中等', low: '持续性低' }, readGuide: '阅读指南', missingTitle: '原居住州仍会向您征税吗？', missingDescription: '州居住规则取决于具体事实。FileAbroad会查看住所、州联系和收入来源，帮助您确定下一步。', start: '开始免费表单', ctaTitle: '对州税有疑问？', ctaDescription: '答案取决于州、联系和收入。让我们先确认您的事实。', ctaButton: '获取申报建议' },
    forms: { label: '税务表格库', title: '海外美国人的IRS税务表格', description: '用中文解释海外居民最重要的税务表格，包括谁需要申报、申报什么、常见错误以及FileAbroad可以提供的帮助。', readGuide: '阅读指南', missingTitle: '不知道需要哪些表格？', missingDescription: '正确的表格取决于国家、收入类型、海外账户和资产。FileAbroad会先审核事实并书面确认范围。', start: '开始免费表单', ctaTitle: '表格只是第一步', ctaDescription: '理解表格是第一步，准确申报才是保护。', ctaButton: '查看所有服务' },
    intake: { eyebrow: '从这里开始', title: 'FileAbroad税务信息表', description: '感谢您咨询美国报税服务。这份简短表格约需3分钟，有助于准备初步审核。回答越准确，我们越能建议合适的下一步。', step: '步骤', of: '/', back: '返回', next: '下一步', submit: '提交', submitting: '正在提交...', privacy: '此表格仅收集初步事实。敏感税务文件请通过安全的Encyro门户提交。' },
  },
};

export type LocalizedPageCopy = HubCopy;
