import type { Locale } from './config';

type ResourceCopy = {
  badge: string;
  title: string;
  description: string;
  leadTitle: string;
  leadDescription: string;
  bonusTitle: string;
  faqTitle: string;
  ctaTitle: string;
  ctaDescription: string;
  ctaButton: string;
};

export const localizedResourceCopy: Record<Locale, ResourceCopy> = {
  en: { badge: 'Free Resource', title: 'The Expat Tax Checklist (2026)', description: 'The essential pre-move, mid-year, and post-move checklist for Americans filing taxes from abroad. Use it yourself or share it with someone planning a move.', leadTitle: 'Get the Printable PDF + Bonus Items', leadDescription: "Enter your email and we'll send you the printable PDF version with 5 bonus items not shown here.", bonusTitle: 'Bonus Items (PDF Only)', faqTitle: 'Frequently Asked Questions', ctaTitle: 'Have Questions About Your Checklist?', ctaDescription: "Every expat situation is different. If something on this list doesn't apply—or you're not sure—start the free intake and Chip will review your facts.", ctaButton: 'Start the 3-Minute Intake' },
  es: { badge: 'Recurso gratuito', title: 'Lista de verificación fiscal para expatriados (2026)', description: 'La lista esencial antes de mudarse, durante el año y después de mudarse para estadounidenses que presentan impuestos desde el extranjero. Úsela o compártala con alguien que planea mudarse.', leadTitle: 'Obtenga el PDF imprimible y los extras', leadDescription: 'Introduzca su correo electrónico y le enviaremos el PDF imprimible con 5 elementos adicionales que no aparecen aquí.', bonusTitle: 'Elementos adicionales (solo PDF)', faqTitle: 'Preguntas frecuentes', ctaTitle: '¿Tiene preguntas sobre su lista?', ctaDescription: 'Cada situación de expatriado es diferente. Si algo no corresponde o no está seguro, inicie la admisión gratuita y Chip revisará sus hechos.', ctaButton: 'Iniciar la admisión de 3 minutos' },
  pt: { badge: 'Recurso gratuito', title: 'Checklist fiscal para expatriados (2026)', description: 'A checklist essencial antes da mudança, durante o ano e depois da mudança para americanos que declaram impostos no exterior. Use-a ou partilhe-a com quem está a planear mudar.', leadTitle: 'Obtenha o PDF para imprimir e os extras', leadDescription: 'Introduza o seu e-mail e enviaremos o PDF para imprimir com 5 itens adicionais que não aparecem nesta página.', bonusTitle: 'Itens extra (apenas PDF)', faqTitle: 'Perguntas frequentes', ctaTitle: 'Dúvidas sobre a checklist?', ctaDescription: 'Cada situação de expatriado é diferente. Se algo não se aplica ou não tiver certeza, inicie a admissão gratuita para que o Chip analise os seus factos.', ctaButton: 'Iniciar a admissão de 3 minutos' },
  fr: { badge: 'Ressource gratuite', title: 'Checklist fiscale des expatriés (2026)', description: 'La checklist essentielle avant le départ, pendant l’année et après le déménagement pour les Américains qui déclarent depuis l’étranger. Utilisez-la ou partagez-la avec une personne qui prépare son départ.', leadTitle: 'Recevoir le PDF imprimable et les bonus', leadDescription: 'Indiquez votre adresse e-mail et nous vous enverrons le PDF imprimable avec 5 éléments supplémentaires.', bonusTitle: 'Éléments bonus (PDF uniquement)', faqTitle: 'Questions fréquentes', ctaTitle: 'Des questions sur votre checklist ?', ctaDescription: 'Chaque situation d’expatrié est différente. En cas de doute, commencez l’admission gratuite afin que Chip examine vos faits.', ctaButton: 'Commencer l’admission de 3 minutes' },
  de: { badge: 'Kostenlose Ressource', title: 'Steuer-Checkliste für Expats (2026)', description: 'Die wichtige Checkliste vor dem Umzug, während des Jahres und danach für Amerikaner, die aus dem Ausland abgeben. Nutzen oder teilen Sie sie mit jemandem, der einen Umzug plant.', leadTitle: 'Druckbares PDF und Bonus erhalten', leadDescription: 'Geben Sie Ihre E-Mail-Adresse ein; wir senden Ihnen die druckbare PDF-Version mit fünf zusätzlichen Punkten.', bonusTitle: 'Bonusmaterial (nur PDF)', faqTitle: 'Häufige Fragen', ctaTitle: 'Fragen zu Ihrer Checkliste?', ctaDescription: 'Jede Expat-Situation ist anders. Bei Unsicherheit starten Sie die kostenlose Erfassung, damit Chip Ihre Fakten prüft.', ctaButton: '3-Minuten-Erfassung starten' },
  it: { badge: 'Risorsa gratuita', title: 'Checklist fiscale per espatriati (2026)', description: 'La checklist essenziale prima del trasferimento, durante l’anno e dopo il trasferimento per gli americani che presentano la dichiarazione dall’estero. Usala o condividila con chi sta pianificando un trasferimento.', leadTitle: 'Ricevi il PDF stampabile e i bonus', leadDescription: 'Inserisci la tua email e riceverai la versione PDF stampabile con 5 elementi aggiuntivi.', bonusTitle: 'Elementi bonus (solo PDF)', faqTitle: 'Domande frequenti', ctaTitle: 'Domande sulla checklist?', ctaDescription: 'Ogni situazione di espatriato è diversa. In caso di dubbio, inizia la raccolta gratuita e Chip esaminerà i tuoi fatti.', ctaButton: 'Inizia la raccolta di 3 minuti' },
  nl: { badge: 'Gratis hulpmiddel', title: 'Belastingchecklist voor expats (2026)', description: 'De essentiële checklist vóór vertrek, tijdens het jaar en na de verhuizing voor Amerikanen die vanuit het buitenland aangifte doen. Gebruik of deel deze met iemand die een verhuizing plant.', leadTitle: 'Ontvang de printbare PDF en extra’s', leadDescription: 'Vul uw e-mailadres in en ontvang de printbare PDF met vijf extra onderdelen.', bonusTitle: 'Extra onderdelen (alleen PDF)', faqTitle: 'Veelgestelde vragen', ctaTitle: 'Vragen over uw checklist?', ctaDescription: 'Elke expatsituatie is anders. Start bij twijfel de gratis intake zodat Chip uw feiten kan bekijken.', ctaButton: '3-minuten-intake starten' },
  ja: { badge: '無料リソース', title: '海外居住者向け税務チェックリスト（2026年）', description: '海外から申告するアメリカ人が、移住前・年度中・移住後に確認できる実用的なチェックリストです。ご自身で使うことも、移住を計画している人と共有することもできます。', leadTitle: '印刷用PDFと特典を受け取る', leadDescription: 'メールアドレスを入力すると、ページにない5つの特典付きPDFをお送りします。', bonusTitle: '特典（PDFのみ）', faqTitle: 'よくある質問', ctaTitle: 'チェックリストについて質問がありますか？', ctaDescription: '海外居住者の状況はそれぞれ異なります。迷った場合は無料フォームを開始し、Chipが事実関係を確認します。', ctaButton: '3分のフォームを開始' },
  zh: { badge: '免费资源', title: '海外美国人税务清单（2026年）', description: '为从海外申报的美国人准备的搬家前、年度中和搬家后实用清单。您可以自己使用，也可以分享给正在计划搬家的人。', leadTitle: '获取可打印PDF和额外内容', leadDescription: '输入电子邮件，我们会发送包含5项额外内容的可打印PDF。', bonusTitle: '额外内容（仅PDF）', faqTitle: '常见问题', ctaTitle: '对清单有疑问？', ctaDescription: '每个海外居住者的情况都不同。如有疑问，请开始免费表单，让Chip审核您的事实。', ctaButton: '开始3分钟表单' },
};

export type LocalizedResourceCopy = ResourceCopy;
